### PR TITLE
Use dom-event-target for event interface

### LINKED ISSUE #12: Add function removeEventListener
Does it make sense to add a [removeEventListener](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/removeEventListener) function as well for symmetry?

This should also make it possible to do more sugary things like `.once()`

### PR DESCRIPTION
**Pull request by bendrucker**
Adds `removeListener`, otherwise there's feature parity. 

_edit:_ Closes #12

### CODE REVIEW

**Comment by Flet** [comment]
Closes #12 :)

**Comment by bendrucker** [comment]
Indeed it does

**Comment by shama** [comment]
Thanks @bendrucker! I like your API doc style too.

**Comment by bendrucker** [comment]
Thanks! It's a cross between sindresorhus's and Bluebird's.

**Pull request merged**
