### PR TITLE
Fix custom-element example

### PR DESCRIPTION
**Pull request by chinedufn**

### CODE REVIEW

**Comment by bendrucker** [comment]
https://www.npmjs.com/package/webcomponents.js

Wouldn't be much point in the module requiring itself, if you can even do that ;)

**Comment by shama** [comment]
Thanks! But [custom-element](https://www.npmjs.com/package/custom-element) requires the library [webcomponents.js](https://www.npmjs.com/package/webcomponents.js). So `require('webcomponents.js')` there is intentional.

To run that example locally you'll need to `npm i webcomponents.js custom-element` then change the `start` script in the `package.json` to point to `examples/custom-element.js`.

**Comment by chinedufn** [comment]
Ah. Confused that with https://github.com/shama/base-element/blob/master/examples/webcomponent.js

Thanks !

**Comment by shama** [comment]
@chinedufn I just added some notes with more info about each example: https://github.com/shama/base-element/commit/4e1b7e2ce90e0c0f26d6ae392a56dfd0ad3ccd8b :)

**Comment by chinedufn** [comment]
@shama love the extra context. Looks great :)

**Pull request closed without merging**
