### PR TITLE
[wip] base-element: add .toString() method

### LINKED ISSUE #5: .toString()?
When rendering on the server it can be neat to implement a `.toString()` function (or equivalent) to render components to `html`. I'm not sure what the tradeoffs are; but I think it's feasible to implement for every component. Thanks!
### See Also
- [vdom-to-html](https://github.com/nthtran/vdom-to-html)

### PR DESCRIPTION
**Pull request by yoshuawuyts**
wip. Closes https://github.com/shama/base-element/issues/5. Needs tests + docs added. Mostly checking if this is the correct interface. Thanks!
### Changes
- **base-element**: add `.toString()` method which returns stringified html

### CODE REVIEW

**Comment by shama** [comment]
Thanks! I tried this same thing yesterday and it causes a weird issue where `this.element.toString()` also called `this.render()` again for some reason. Simply renaming `toString()` to `toHTML()` fixed it but I wanted to find out why that was occurring.

**Comment by shama** [comment]
Dug into this a bit and it appears to be `var document = require('global/document')` which on the server shims [min-document](https://github.com/Raynos/min-document). Which in turn calls the `toString()` of the element itself thus creating an infinite loop. Still working on a fix...

**Comment by shama** [comment]
Merged with edits: https://github.com/shama/base-element/compare/04953ec953c407bafeaaeb2479ca951e70239556...aff848c0233e0436603b22f178a4aec9fa73571a Thanks!

**Comment by yoshuawuyts** [comment]
:tada: neat!

**Pull request closed without merging**
